name: eprinttools # Caltech Library EPrint Tools
base: core20 # the base snap is the execution environment for this snap
version: '1.1.7' # Development semver
summary: Command line tools and service for working with an EPrints repository
description: |
        eprinttools provides a epfmt, eputil and ep3apid. The first are
        tools for working with EPrint XML and the EPrints REST API. The
        third is a service for interacting with EPrints metadata via
        MySQL.
        connections.
license: BSD-3-Clause
grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

apps:
  epfmt:
        command: bin/epfmt
        plugs:
                - home
  eputil:
        command: bin/eputil
        plugs:
                - home
  ep3apid:
        command: bin/ep3apid
        daemon: simple
        plugs:
                - home
parts:
  eprinttools:
    plugin: go
    go-channel: stable
    build-environment:
            - "CGO_ENABLED" : "0"
    source-type: git
    source: https://github.com/caltechlibrary/eprinttools
